x-sharedconfig: &sharedconfig
  depends_on:
    rabbit:
      condition: service_healthy
  environment:
    - MassTransitConfig__Username=guest
    - MassTransitConfig__Password=guest
    - MassTransitConfig__Uri=rabbit
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ..
      dockerfile: Api/Dockerfile
    <<: *sharedconfig

  handler:
    image: ${DOCKER_REGISTRY-}handler
    build:
      context: ..
      dockerfile: Handler/Dockerfile
    <<: *sharedconfig
    
  emailapi:
    image: ${DOCKER_REGISTRY-}emailapi
    build:
      context: ..
      dockerfile: EmailApi/Dockerfile
    <<: *sharedconfig

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.102.0
    container_name: otel-col
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ../otel-collector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9000:9000"
      - "8888:8888"

  aspiredashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    ports:
      - "18888:18888"
      - "18889:18889"
